### ISSUE TITLE
Create a random test

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#13]
create a simple test case with random costs and dynamics. The aim is to be able to compare the speed with various parameters : dimension of state, number of time stage...

**Comment by Henri-Gerard** [comment]
Does this issues refers to the problem you are currently working on or does it concern the dynamic_example.jl file ?

**Comment by leclere** [comment]
This issue was about your dynamic_example.jl file. I will have a look at it later on.
