### ISSUE TITLE
Add use of solver preprocessing for pruning

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#130]

**Comment by odow** [comment]
Whats the idea behind this?

**Comment by leclere** [comment]
@odow 

The idea is to write the Bellman function as a linear program with constraint like \alpha \geq cut.
Then you can call a linear solver (like CPLEX) preprocessing (by taking maxitnumber = 0) to eliminate all useless cut. This should be faster than testing all constraints while remaining exact.

**Comment by odow** [comment]
Interesting idea. And then you add back in the constraints for the dynamics?

@lkapelevich another interesting idea to benchmark

**Comment by frapac** [comment]
Move issue to CutPruners.jl
