### ISSUE TITLE
StochDynamic Programming Fails to Load in Julia 1.0 (Nullable not defined) 

### ISSUE THREAD

**Issue by kirui93** [JuliaStochOpt/StochDynamicProgramming.jl#171]
I get the following error while trying to use it.

┌ Info: Precompiling StochDynamicProgramming [f6024387-75e5-5fdf-b095-327b05c0905f]
└ @ Base loading.jl:1186
ERROR: LoadError: LoadError: UndefVarError: Nullable not defined
Stacktrace:

any fixes?

**Comment by frapac** [comment]
We are currently updating StochDynamicProgramming to Julia 1.0 and JuMP 0.19. 
The current development branch is [moi](https://github.com/JuliaStochOpt/StochDynamicProgramming.jl/tree/moi). SDDP and extensive formulation are currently working, but it remains to port Dynamic Programming to Julia 1.0. 

This branch is about to be merged in master.

**Comment by kirui93** [comment]
So it means that if I want to use it now, I should downgrade Julia to which version?

**Comment by frapac** [comment]
Solved with #173
