### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#20]
Instead of a display Boolean, I suggest an integer, with something along the line of
if display >0 && mod(counter,display)==0 
   println(...)
end

**Comment by Henri-Gerard** [comment]
Est-ce que tu peux merger la PR de François ? Il a pas internet c'est pour
ça que c'est moi qui écris le mail. C'est pour qu'il puisse commencer à
régler les conflits

**Comment by frapac** [comment]
Done in branch upd-user-interface
