### ISSUE TITLE
display as integer

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#36]
display should be an integer (0 for false, everything else for true, and when possible printing every display iteration).

**Comment by frapac** [comment]
Is'nt it the case already?

**Comment by leclere** [comment]
Actually it is not closed because not dealt with in SDPoptimize. I fear for incompatibility later on. 

I also think we should catch display as boolean in SDDPoptimize.

**Comment by frapac** [comment]
I think we could close this issue
