### ISSUE TITLE
ctrl C does not interrupt the optim

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#38]

**Comment by frapac** [comment]
Yes it does ! But I think we ought to catch properly the exception

**Comment by leclere** [comment]
I have been able to reproduce the problem : when I call stock-example ctrl-C does not interrupt sddp computation.

**Comment by frapac** [comment]
It works on my laptop. But again, I do not think that this is the proper way to do unless we catch explicitly the exception Interrupt.
