### ISSUE TITLE
Default if interpolation is missing

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#49]
If the package interpolation is missing we should print a warning and default to nearest neighbours instead of failing.

**Comment by trigaut** [comment]
I correct that ASAP. I have to add some unit tests for the SDP part as well.

**Comment by odow** [comment]
Interpolations shouldn't be missing as you have it in your require file https://github.com/leclere/StochDynamicProgramming.jl/blob/master/REQUIRE#L8

**Comment by leclere** [comment]
@odow you are probably right. I close the subject for now.
