### ISSUE TITLE
Inconsistency with final time step

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#50]
There is still some inconsistencies with the final step. We should unify this over the package to help any users.

**Comment by frapac** [comment]
Could you point out the files where are the inconsistencies?

**Comment by trigaut** [comment]
Yes I thought that we solved this issue?

**Comment by Henri-Gerard** [comment]
I thought also that now T = model.stageNumber-1. If you point out where are the inconsistencies, I can take care of it

**Comment by trigaut** [comment]
To be clear in sdp I started with TF = number of time steps in the control vector. So the constructor of sddp needed the number of stages while the constructor of sdp needed this number minus 1. I changed it to be more consistent and now both constructors need the number of stages (the number of time steps in the state vector). I think you should do the same thing Henri if it's not the case.
