### ISSUE TITLE
get_control functions

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#51]
We need some get_opt_control(SPmodel,params,x,t,xi,V) functions. They could factorize the code and are required for the examples.

**Comment by leclere** [comment]
In the same idea we need need some get_value(SPmodel, params, x,t,V)

**Comment by frapac** [comment]
It exists: SDDPOptimize.jl, line 418

**Comment by leclere** [comment]
Yes, we don't have the equivalent for SDP resolution ( nor for EF). And I'm not sure if we have the get_opt_control for SDDP.

**Comment by frapac** [comment]
I think oneStepPerAlea is sufficient to do this.

**Comment by leclere** [comment]
probably but the name is not easy to guess for someone who does not want to know the inside of the algorithm.

I think it is reasonable to assume that someone can solve its problem, and then ask to get the optimal control at a given point with a function dedicated for it.

**Comment by frapac** [comment]
I think we could close this issue
