### ISSUE TITLE
Convert Int64 in Int and Float64 in Float

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#61]
It seems that it would be a good idea to convert every Int64 in Int, and Float64 in Float. We might need confirmation on the subject before going along.

**Comment by odow** [comment]
You should use probably use `Int` instead of `Int64` but use `Float64` as there is no `Float` alias.

Have a look at https://github.com/JuliaLang/julia/issues/12188
