### ISSUE TITLE
Return controls ands states with extensive formulation

### ISSUE THREAD

**Issue by trigaut** [JuliaStochOpt/StochDynamicProgramming.jl#67]
I think extensive formulation currently returns only the optimal cost and the status. Shouldn't we add controls and states?

**Comment by leclere** [comment]
Returning the first control is a good idea. 

Returning a trajectory of states and control along a given scenario found by extensive formulation would be a good idea but might be complex to implement.

**Comment by Henri-Gerard** [comment]
Ok I'll take care of it
