### ISSUE TITLE
Integrate to JuliaOpt

### ISSUE THREAD

**Issue by leclere** [JuliaStochOpt/StochDynamicProgramming.jl#76]
Start the process of adding the package to the JuliaOpt's METADATA 
@mlubin @joehuchette

**Comment by mlubin** [comment]
@leclere, looking forward to welcoming this package into JuliaOpt. Ping us again after @IainNZ's comments have been addressed

**Comment by leclere** [comment]
@mlubin  @IainNZ we have addressed the comments to the best of our knowledge. The package is now in Julia METADATA, in case it helps.

Thanks again for your comments.

**Comment by mlubin** [comment]
Looks good on my end.
CC @madeleineudell @tkelman

**Comment by mlubin** [comment]
If there are no comments from other JuliaOpt folks in the next week then I'll go ahead and transfer the repo.

**Comment by mlubin** [comment]
@leclere, I've invited you to JuliaOpt with temporary admin permissions. Once you accept, you can go to https://github.com/leclere/StochDynamicProgramming.jl/settings and transfer ownership of the repo into JuliaOpt.

**Comment by leclere** [comment]
@mlubin Thanks, I transfered the repo. I also created a team with the people currently working on the project and gave them write permission. Let me know if there is anything else I should or could do.

**Comment by mlubin** [comment]
Awesome. Please announce the new JuliaOpt repository on the julia-opt list. We're going to have to update the website but a makeover is overdue.
