### ISSUE TITLE
Thoughts on REQUIRE file

### ISSUE THREAD

**Issue by IainNZ** [JuliaStochOpt/StochDynamicProgramming.jl#80]
Hey,

I was looking at your REQUIRE file, and see
- FactCheck -- this is probably better in the `test/REQUIRE` file
- Clp -- is it necessary to require a specific solver? Some users might want to just provide their own, and not have to build/install Clp
- MathProgBase -- you get this through JuMP. So not necessary in the REQUIRE, but not wrong to include. My suggestion would be to remove.

**Comment by leclere** [comment]
@IainNZ Hello, thanks a lot for your comments. We are working on it.

About Clp : we need one solver for the package to work, what is the best way to check that one solver is available and if not to suggest to install Clp ?
