### ISSUE TITLE
JuMP syntax

### ISSUE THREAD

**Issue by IainNZ** [JuliaStochOpt/StochDynamicProgramming.jl#82]
I noticed you are using the JuMP v0.12-and-earlier syntax. Before releasing, I'd suggest updating to JuMP v0.13 syntax (which is simple find and replace), and in your REQUIRE file specifying `JuMP 0.13`.

**Comment by leclere** [comment]
@IainNZ Thanks for your remarks they were taken into account in the dev-release-v0.1.2 branch that should be released soon.
